### ISSUE TITLE
[Question] Walking Robot Interface

### ISSUE THREAD

**Issue by araffin** [GoodAI/SpaceEngineersGym#3]
Hello,

I have some questions/remarks regarding the walking robot env.

## Observation space

https://github.com/GoodAI/SpaceEngineersGym/blob/9b5b7f7ea4d682005ddf59e64e2931b9796ad860/gym_space_engineers/envs/walking_robot_ik.py#L16

I assume it is not up to date?

For validating the Gym env, I would recommend you to use the SB3 env checker ;)
```python
from stable_baselines3.common.env_checker import check_env

env = CustomEnv(arg1, ...)
# It will check your custom environment and output additional warnings if needed
check_env(env)
```

>- Position of the body as a 3-dimensional vector (X, Y, Z)
>- Forward direction of the robot as a 3-dimensional vector (X, Y, Z)

you mean (vx, vy, vz) ?

> Up direction of the robot as a 3-dimensional vector (X, Y, Z)

up direction?

>- Actual positions of end-effectors of all the legs as an array of shape (6, 3)

Could we also have orientation (3 angles) + angular velocity of the robot?
And for the joints (legs), do we have any torque/contact sensor too?

## Action Space

>- For each leg a 4-dimensional vector with instructions for the inverse kinematics - (X, Y, Z, Speed)
>  - (X, Y, Z) is the goal position for the end-effector of a given leg, in a coordinate system relative to the joint with which the leg is attached to the body
>- A distance-proportional controller is used to control the speed of the leg (the maximum allowed speed is controlled with the Speed parameter)

~I'm not sure to understand what we command: do we command (vx, vy, vz) or do we command the motor in position and speed is the max speed at which the position will be reached?~ (found my answer later in the spec)

>We are only working with inverse kinematics, not directly controlling the joints

how much effort would it be to have it as a parameter to the env? (if too much effort, let's keep it as is for now).

https://github.com/GoodAI/SpaceEngineersGym/blob/9b5b7f7ea4d682005ddf59e64e2931b9796ad860/gym_space_engineers/envs/walking_robot_ik.py#L19

Why are the limits infinite? We command the end effector in absolute position?
The action should be normalized and symmetric (`low=-1, high=1` and the rescaling is done inside the env) and also we should flatten the shape to avoid any issue (so have a 1D vector of size `self.number_of_legs * 4`)

## Reward function

unless you plan to rewrite the env, I will create a branch to include a reward function + termination condition.

## Render

Is there a way to retrieve an image of the robot as numpy array? (using a camera looking at it)

## Additional remarks

https://github.com/GoodAI/SpaceEngineersGym/blob/9b5b7f7ea4d682005ddf59e64e2931b9796ad860/gym_space_engineers/envs/walking_robot_ik.py#L14

what is detach parameter?

**Comment by araffin** [comment]
Additional question: what is the control frequency of the robot? Is there an easy way to set/limit it? 
(around 15-30Hz should be enough)

**Comment by OndrejNepozitek** [comment]
Thanks for the feedback. Please keep in mind that the interface for the walking robots is being developed primarily for the upcoming hackathon and any future research in this direction but it hasn't been used yet in any real-life scenario. Therefore, there are many rough edges, missing documentation and we often had to guess what would be useful for you rather than base our decisions on our experience. So pretty much everything is subject to change.

> I assume it is not up to date?

Yeah, the observation space is not up to date but the env already returns some observations.

> For validating the Gym env, I would recommend you to use the SB3 env checker ;)

Thanks, I'll look into that.

> Forward direction of the robot as a 3-dimensional vector (X, Y, Z)
> Up direction of the robot as a 3-dimensional vector (X, Y, Z)

This is actually the orientation of the robot. The first is the forward-facing vector of the robot, i.e. the direction in which the robot is currently looking, relative to the sandbox environment. So if you spawn the robot in the environment, the forward vector is approximately equal to (0,0,-1) because that's the Forward direction in Space Engineers. And the second is the upwards-facing vector which is initially equal to (0,1,0) because that's the Up direction in Space Engineers. I'll also add the Right direction vector so that the orientation is clear without knowing the internals of Space Engineers.

> Could we also have orientation (3 angles) + angular velocity of the robot?

The orientation is currently described with the 3 direction vectors because that's what provided by Space Engineers by default. 

>  + angular velocity of the robot?

This could be added but I'm not sure if I can do it before the hackathon.

> And for the joints (legs), do we have any torque/contact sensor too?

We don't have any of that right now.

> > We are only working with inverse kinematics, not directly controlling the joints

> how much effort would it be to have it as a parameter to the env? (if too much effort, let's keep it as is for now).

We would like to keep it as it is for the hackathon and we can discuss any possible modifications after that.

> Why are the limits infinite? We command the end effector in absolute position?
> The action should be normalized and symmetric (low=-1, high=1 and the rescaling is done inside the env) 

The commands are relative to the first joint of each leg. The bounds are currently infinite because, in theory, we don't know anything about the actual shape of the legs as they can be constructed by users. I can probably assume that no leg will be more than 20 meters long and set the bounds to [-1,1] and then scale that to [-20,20]. Or try to infer this information from the computed inverse kinematics model (supposing that we have one for each robot that will be eventually available in the gym). What do you think about that?

> and also we should flatten the shape to avoid any issue (so have a 1D vector of size self.number_of_legs * 4)

I can do that.

> unless you plan to rewrite the env, I will create a branch to include a reward function + termination condition.

Our goal was to just provide all the information that might be useful to construct a reward function and leave it to users of the gym to actually decide the values of the reward. So feel free to branch/fork the repo to add your own reward function. It could probably also be possible to just wrap the call to the step function and compute the reward there.

> Is there a way to retrieve an image of the robot as numpy array? (using a camera looking at it)

It's possible in theory but we don't have an infrastructure for that yet.

> what is detach parameter?

This is mostly just for debugging purposes as each robot is usually spawned with a scaffolding that prevents the robot from moving away from its spawn position. If the detach parameter is set to false, the robot will stay on that scaffolding and it's easier to test that the commands sent to the robot work as expected.

> Additional question: what is the control frequency of the robot? Is there an easy way to set/limit it?
(around 15-30Hz should be enough)

By default, the physics simulation runs at 60 UPS (updates per second) and the gym can therefore control the robot at 60Hz. The network interface is asynchronous - meaning that we can probably use a simple timer in Python to make sure that we send at most 15/30 commands per second. If there are no new commands coming to the game, the game will just repeat the previous command. If needed, we can also increase the speed of the game to probably more than 300 UPS, meaning that if we can send the commands fast enough, we can do much more work in Space Engineers.

**Please let me know if any of the questions/suggestions are critical for the upcoming hackathon as there's probably not enough time to handle everything before the hackathon starts.**

**Comment by araffin** [comment]
>Please keep in mind that the interface for the walking robots is being developed primarily for the upcoming hackathon and any future research in this direction but it hasn't been used yet in any real-life scenario. Therefore, there are many rough edges, missing documentation and we often had to guess what would be useful for you rather than base our decisions on our experience. So pretty much everything is subject to change.

no worry, that's what I was assuming ;)

>This is actually the orientation of the robot. The first is the forward-facing vector of the robot, i.e. the direction in which the robot is currently looking, relative to the sandbox environment. 

Do you have a diagram/image with those two vectors? I have to admit it is quite unintuitive to me, and it's really important for learning to get those quantities right.

>The bounds are currently infinite because, in theory, we don't know anything about the actual shape of the legs as they can be constructed by users. 

I see...

>Or try to infer this information from the computed inverse kinematics model (supposing that we have one for each robot that will be eventually available in the gym). What do you think about that?

That's where commanding joint angles would be easier...

For now, let's assume we can retrieve the limits from the IK model.

>By default, the physics simulation runs at 60 UPS (updates per second) and the gym can therefore control the robot at 60Hz.

Ok, thanks, we may need to slow down the python control rate (we'll see).

>Please let me know if any of the questions/suggestions are critical for the upcoming hackathon as there's probably not enough time to handle everything before the hackathon starts.

Apart from normalizing the action space and clarifying the coordinate system, I should manage to prepare the rest ;)

(I'm currently adapting the gym interface that I was using to learn locomotion on the real robot and the part I'm struggling with now is the coordinate system)

**Comment by OndrejNepozitek** [comment]
Here are two screenshots after the robot is spawned in the world together with values of all 3 vectors.

![image](https://user-images.githubusercontent.com/2265359/116101919-8a50bf00-a6ae-11eb-9de2-726af19d650b.png)

![image](https://user-images.githubusercontent.com/2265359/116102207-cd129700-a6ae-11eb-8640-0ae242f19999.png)

Here is a screenshot of how the vectors look if we rotate the robot by 90 degrees counterclockwise.

![image](https://user-images.githubusercontent.com/2265359/116102598-224ea880-a6af-11eb-9351-2c39caed6fa6.png)

Is this more clear now?

**Comment by araffin** [comment]
>Is this more clear now?

Thank you very much.

I made a diagram to check we are on the same page ;) (I think the confusion came for just a different terminology, I usually use global/world coordinates vs local/robot coordinates)

![space_coords](https://user-images.githubusercontent.com/1973948/116113043-6d20ee00-a6b8-11eb-804c-b5c7615396b5.png)

**Comment by araffin** [comment]
Looking at the code again, one thing is not clear: is there a way to get the initial observation without sending any action? (or sending a dummy action)

**Comment by OndrejNepozitek** [comment]
> I made a diagram to check we are on the same page ;)

I think we're on the same page. 

> Looking at the code again, one thing is not clear: is there a way to get the initial observation without sending any action? (or sending a dummy action)

I'll add that as an output from the reset() function. The reset() function should also move the robot back to the initial spawn point which is not yet reflected in the source code but should be done before the hackathon.

**Comment by araffin** [comment]
>I think we're on the same page.
>I'll add that as an output from the reset() function. The reset() function should also move the robot back to the initial spawn point which is not yet reflected in the source code but should be done before the hackathon.

perfect =)

> The commands are relative to the first joint of each leg. The bounds are currently infinite because, in theory, we don't know anything about the actual shape of the legs as they can be constructed by users.

btw, I thought of something potentially better: make the desired position relative and not absolute (that would solve our issue, no? it will only restrict the action space a bit)

**Comment by OndrejNepozitek** [comment]
> btw, I thought of something potentially better: make the desired position relative and not absolute (that would solve our issue, no? it will only restrict the action space a bit)

I'm not sure I understand. The position is already relative. If I send a command (1, 2, 3, 1) it means that a given leg should move 1 meter to the right of the shoulder joint, 2 meters up and 3 meters backwards with the maximum speed.

Edit: Or do you mean relative as in I choose the maximum size of the action space to be 20 meters in each direction and then I'll use the value of 0.1 to represent 2 meters in the game?

**Comment by araffin** [comment]
>The position is already relative. 

Ah ok, that was not clear to me. 

Btw, what is the scale of SE robots? (one robot is ~1m? ~10m long ?)

>with the maximum speed.

Looking at the code, I thought maximum speed was 100... unless you were using scaled value?

>Edit: Or do you mean relative as in I choose the maximum size of the action space to be 20 meters in each direction and then I'll use the value of 0.1 to represent 2 meters in the game?

hmm, to clarify, there is mainly two ways to tackle the problem here:
- command a delta in position (relative command to the current position of the EE)
- command an absolute desired position for the EE

**Comment by OndrejNepozitek** [comment]
>Btw, what is the scale of SE robots? (one robot is ~1m? ~10m long ?)

The robot on the screenshot above is I think below 10 meters/units long.
